name: Node CI

description: Build and run tests on node

runs:
  using: composite
  timeout-minutes: 10
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: 'yarn'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@almer-technologies'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Check types
      run: yarn type-check

    - name: Check linting
      run: yarn lint

    - name: Run tests
      run: yarn test:ci

    - name: Build package
      run: yarn build

    - name: Check commits messages
      uses: wagoid/commitlint-github-action@v5
