name: Node CI

description: Build and run tests on node

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: 'yarn'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@almer-technologies'

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Check types
      run: yarn type-check
      shell: bash

    - name: Check linting
      run: yarn lint
      shell: bash

    - name: Run tests
      run: yarn test:ci
      shell: bash

    - name: Build package
      run: yarn build
      shell: bash

    - name: Check commits messages
      uses: wagoid/commitlint-github-action@v5

    - run: echo "DONE"
      shell: bash
